version: '3.6'
services:
  hasura:
    network_mode: bridge
    image: hasura/graphql-engine:v1.0.0-alpha36
    ports:
      - '8080:8080'
    links:
      - postgres
    depends_on:
      - postgres
      - pgAdmin
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://root:prisma@postgres:5432/gql
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## uncomment next line to set an access key
      # HASURA_GRAPHQL_ACCESS_KEY: mysecretaccesskey
  postgres:
    image: postgres:10.5
    network_mode: bridge
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '${POSTGRES_PORT_FORWARDED}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    network_mode: bridge
    restart: always
    links:
      - postgres
      # - plv8
    ports:
      - '9090:80'
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: '${POSTGRES_USER}'
      PGADMIN_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'
volumes:
  postgres_data:
